# This is meant to run the server locally, and without TLS, 
# saving the demoing user the trouble of getting certs and keys.

name: archie
services:
  svr:
    build: .
    ports:
      - "3000:4949"
    # if running with sudo, use the --preserve-env option
    # so that your user shell env is in scope
    environment:
      # DB host needs to be CONTAINER name not service name
      DB_URL: mysql://server1:the-pass@archie-db:3306/archie
      RUST_LOG: "archie_server=debug"   # for `tracing` logger
      PY_CONT_SOCK: "lb-app:3575"
    command: ["./target/release/archie-server", "--no-tls"]
    # allows web content to be loaded in on compose, not requiring rebuild
    volumes:
      - type: bind
        source: ./demo.log
        target: /home/server/archie-server.log
      - type: bind
        source: ./pages
        target: /home/server/pages
      - type: bind
        source: ./static
        target: /home/server/static
      - type: bind
        source: ./node_modules
        target: /home/server/node_modules

  db:
    image: "mysql:9.2"
    container_name: "archie-db"
    volumes:
      - type: bind
        source: "./db-init-demo/"
        # all scripts in this directory will be run
        target: "/docker-entrypoint-initdb.d"
      - type: bind
        source: "./backup_on_exit.sh"
        target: "/backup_on_exit.sh"
    entrypoint: ["bash", "backup_on_exit.sh"]
    command: "mysqld"
    healthcheck:
      # slight breach of exec form with the options, but `mysqladmin` does not work otherwise
      test: [ "CMD", "mysqladmin", "ping", "--user=server1", "--password=the-pass" ]
      interval: 15s
      retries: 3
      start_period: 1m
    environment:
        MYSQL_ONETIME_PASSWORD: false
        MYSQL_ALLOW_EMPTY_PASSWORD: false
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_USER: server1
        MYSQL_PASSWORD: the-pass 

  lb-app:
    build: ./letterboxd_get_list
    container_name: "lb-app"
    volumes:
      - type: bind
        source: "./letterboxd_get_list/valid-lb-attrs.txt"
        target: "/valid-lb-attrs.txt"