name: archie
services:
  svr:
    build: .
    container_name: "archie-svr"
    ports:
      - "8080:4949"
    # needs double $ to read from shell env
    environment:
      DB_URL: mysql://server1:$${MYSQL_PASSWORD?}@db:33061/archie
    volumes:
      - type: bind
        source: ./archie-server.log
        target: /home/server/archie-server.log
    secrets:
      - server-cert
      - server-priv-key

  db:
    image: "mysql:9.2"
    container_name: "archie-db"
    ports:
      - "33061:3306"
    volumes:
      - type: bind
        source: "./db-init/"
        # all scripts in this directory will be run
        target: "/docker-entrypoint-initdb.d"
      - type: bind
        source: "./backup_on_exit.sh"
        target: "/backup_on_exit.sh"
    entrypoint: ["bash", "backup_on_exit.sh"]
    command: "mysqld"
    environment:
        MYSQL_ONETIME_PASSWORD: false
        MYSQL_ALLOW_EMPTY_PASSWORD: false
  
secrets:
  server-cert:
    file: fullchain.pem
  server-priv-key:
    file: privkey.pem