name: archie
services:
  svr:
    # separately-built image to avoid clutter from anonymous images
    image: lmr97/archie-svr:latest
    restart: always
    depends_on:
      - db
      - lb-app
    ports:
      - "8080:4949"
    environment:
      PRE_LOG: 1
      # DB host needs to be CONTAINER name not service name
      DB_URL: mysql://server1:${MYSQL_PASSWORD:-my-sql-passwd}@archie-db:3306/archie
      RUST_LOG: "debug"   # for `tracing` logger
      PY_CONT_SOCK: "lb-app:3575"
    command: [ "/home/server/custom-backend/target/release/archie-server", "--no-tls"]
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:4949" ]
      interval: 30s
      retries: 5
      start_period: 2s
    volumes:
      - type: bind
        source: ./archie-server.log
        target: /home/server/archie-server.log

  db:
    image: mysql:9.2
    restart: always
    container_name: "archie-db"
    volumes:
      - type: bind
        source: "./db-init-demo/"
        # all scripts in this directory will be run
        target: "/docker-entrypoint-initdb.d"
      - type: bind
        source: "./backup_on_exit.sh"
        target: "/backup_on_exit.sh"
    entrypoint: ["bash", "backup_on_exit.sh"]
    command: "mysqld"
    healthcheck:
      # slight breach of exec form with the options, but `mysqladmin` does not work otherwise
      test: [ "CMD", "mysqladmin", "ping", "--user=server1", "--password=${MYSQL_PASSWORD:-my-sql-passwd}" ]
      interval: 15s
      retries: 3
      start_period: 1m
    environment:
        MYSQL_ONETIME_PASSWORD: false
        MYSQL_ALLOW_EMPTY_PASSWORD: false
        MYSQL_USER: server1
        MYSQL_PASSWORD: ${MYSQL_PASSWORD:-my-sql-passwd}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-r00t}   # non-priv user created after startup

  lb-app:
    image: lmr97/lb-web-app:latest
    container_name: "lb-app"
    restart: always
