[package]
name = "custom-backend"
version = "0.3.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.1", features = ["json"] }
axum-server = { version = "0.7.1", features = ["tls-rustls"] }
chrono = "0.4.39"
mysql = { version = "26.0.0", features = ["chrono"] }
mysql_common = "0.34.1"
serde = "1.0.217"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.6.2", features = ["fs"] }
