[package]
name = "custom-backend"
version = "0.2.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
mysql = { version = "26.0.0", features = ["chrono"] }
mysql_common = "0.34.1"
serde = "1.0.217"
serde_derive = "1.0.217"
tokio = { version = "1", features = ["full"] }
warp = { version = "0.3", features = ["tls", "compression"] }
