- name: Deploy latest passing commit
  hosts: web_server
  gather_facts: true

  tasks: 
    - name: Pull new source code
      ansible.builtin.git:
        repo: https://github.com/lmr97/archie-server.git
        dest: ~/archie-server

    # it appears that we must do this manually
    - name: Load MySQL password from environment
      ansible.builtin.shell: 
        cmd: source ~/.user_env && echo $MYSQL_PASSWORD
      register:
        mysql_pass

    - name: Load MySQL root password from environment
      ansible.builtin.shell: 
        cmd: source ~/.user_env && echo $MYSQL_ROOT_PASSWORD
      register:
        mysql_root_pass
    
    - name: Shut down server, back up DB
      community.docker.docker_compose_v2:
        cli_context: rootless
        project_src: ~/archie-server
        files: 
          - compose-no-tls.yaml
        state: absent
      environment: 
        MYSQL_PASSWORD: "{{ mysql_pass.stdout }}"
        MYSQL_ROOT_PASSWORD: "{{ mysql_root_pass.stdout }}"       
    
    - name: Find latest database dump
      ansible.builtin.shell:
        chdir: ~/archie-server/db-dumps/
        cmd: ls -t | head -n 1
      register: latest_dump

    - name: Check database dump
      ansible.builtin.shell: 
        chdir: ~/archie-server
        cmd: bash test-helpers/validate-dump.sh
      register: db_dump_validation

    - name: Copy dump into production database file
      ansible.builtin.shell:
        chdir: ~/archie-server
        cmd: cp "db-dumps/{{ latest_dump.stdout }}" db-init/db_schema.sql
      when: db_dump_validation is not failed

    # this needs to be a script, because the Ansible module
    # doesn't allow non-3306 ports for the DB on localhost
    # (I want to use 3306 for the Docker pod, and 3307 for
    # the localhost-running DB which will server as backup)
    - name: Back up latest dump to extra-server database
      ansible.builtin.shell: 
        chdir: ~/archie-server/db-dumps
        cmd: mariadb --user=server1 --password="{{ mysql_pass.stdout }}" --execute "source {{ latest_dump.stdout }}"
      when: db_dump_validation is not failed
      register: backup_result
    
    # For security
    - name: Remove latest dump file
      ansible.builtin.shell:
        chdir: ~/archie-server/db-dumps
        cmd: rm "{{ latest_dump.stdout }}"
      when: backup_result is not failed

    - name: Launch server
      community.docker.docker_compose_v2:
        cli_context: rootless
        project_src: ~/archie-server
        files: 
          - compose-no-tls.yaml
        pull: always
        state: present 
      environment: 
        MYSQL_PASSWORD: "{{ mysql_pass.stdout }}"
        MYSQL_ROOT_PASSWORD: "{{ mysql_root_pass.stdout }}"
