- name: Deploy latest passing commit
  hosts: web_server
  remote_user: martinr

  tasks: 
    - name: Pull new source code
      ansible.builtin.git:
        repo: https://github.com/lmr97/archie-server.git
        dest: ~/archie-server-ansible

    # - name: Shut down server, back up DB
    #   community.docker.docker_compose_v2:
    #     project_src: ~/archie-server-ansible
    #     state: absent
    
    - name: Get latest database dump
      ansible.builtin.shell:
        chdir: ~/archie-server-ansible
        cmd: |
          cp db-dumps/db_schema_2025-07-09T23:11.sql "db-dumps/db_schema_$(date +'%Y-%m-%dT%H:%I').sql"
          NOW_MINUTE=$(date +"%Y-%m-%dT%H:%I")
          ls db-dumps | grep ${NOW_MINUTE}
      register: latest_dump
    
    - name: Check database dump
      ansible.builtin.shell: 
        chdir: ~/archie-server-ansible
        cmd: bash test-helpers/validate-dump.sh
      register: db_dump_validation

    - name: Copy dump into production database file
      ansible.builtin.shell:
        chdir: ~/archie-server-ansible
        cmd: cp db-dumps/{{ latest_dump.stdout }} db-init/db_schema.sql
      when: db_dump_validation is not failed

    - name: Back up latest dump to extra-server database
      community.mysql.mysql_query:
        login_db: archie
        login_user: server1
        login_password: s3rv3r-pass
        query: source latest_dump.stdout
      when: db_dump_validation is not failed

    # - name: Launch server
    #   community.docker.docker_compose_v2:
    #     project_src: ~/archie-server-ansible
    #     pull: always
    #     recreate: always
    #     state: present


    # - name: Make new text file with content
    #   ansible.builtin.shell:
    #     chdir: ~/archie-server-ansible
    #     creates: ansible-ran-here.txt
    #     cmd: echo 'ansible ran here!' > ansible-ran-here.txt