- name: Deploy latest passing commit
  hosts: web_server
  gather_facts: true

  tasks: 
    - name: Deploy new image for main server
      kubernetes.core.k8s:
        state: present
        kind: Deployment
        name: archie-main-svr
        namespace: archie
        wait: true
        validate_certs: false
        # k3s puts its kubeconfig in a different place than
        # mainline K8s
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        definition:
          spec:
            template:
              spec:
                containers:
                - name: archie-svr
                  image: lmr97/archie-svr:latest
                  imagePullPolicy: Always
        
    - name: Deploy new image for Letterboxd app
      kubernetes.core.k8s:
        state: present
        kind: Deployment
        name: archie-main-svr
        namespace: archie
        wait: true
        validate_certs: false
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        definition:
          spec:
            template:
              spec:
                containers:
                - name: lb-app
                  image: lmr97/lb-web-app:latest
                  imagePullPolicy: Always
