- name: Deploy latest passing commit
  hosts: web_server
  # remote_user: martin

  tasks: 
    - name: Pull new source code
      ansible.builtin.git:
        repo: https://github.com/lmr97/archie-server.git
        dest: ~/archie-server
    
    - name: Shut down server, back up DB's
      community.docker.docker_compose_v2:
        project_src: ~/archie-server
        state: absent
    
    - name: Check database dump
      ansible.builtin.shell: 
        chdir: ~/archie-server
        cmd: source test-helpers/validate-dump.sh
      register: db_dump_validation

    - name: Copy dump into production database file
      ansible.builtin.shell:
        chdir: ~/archie-server
        cmd: |
          NOW_MINUTE=$(date +"%Y-%m-%dT%H:%I")
          LATEST_DUMP="$(ls db-dumps | grep ${NOW_MINUTE})"
          cp db-dumps/$LATEST_DUMP db-init/db_schema.sql
          echo $LATEST_DUMP
      when: db_dump_validation is not failed
      register: latest_dump

    - name: Back up latest dump to extra-server database
      community.mysql.mysql_query:
        chdir: ~/archie-server
        login_db: archie
        login_user: server1
        login_password: s3rv3r-pass
        query: source latest_dump.stdout
      when: db_dump_validation is not failed

    - name: Launch server
      community.docker.docker_compose_v2:
        project_src: ~/archie-server
        pull: always
        recreate: always
        state: present


    # - name: Make new text file with content
    #   ansible.builtin.shell:
    #     chdir: ~/archie-server
    #     creates: ansible-ran-here.txt
    #     cmd: echo 'ansible ran here!' > ansible-ran-here.txt