name: Archie CI

on:
  push:
    branches: [ "main", "testing" ]

jobs:

  server_tests:

    runs-on: ubuntu-latest
    env:
      EX_VAR: "a value/here"      # an env var to test env fetches
      SERVER_SOCKET: "127.0.0.1:4321"
    defaults:
      run:
        shell: bash
        working-directory: ./custom-backend

    steps:
    - uses: actions/checkout@v4   # checks out the repo
    # - name: Build server
    #   run: cargo build
    - name: Set up MySQL database
      # uses mock database from repo; allows for 
      run: |
        docker compose --file ../compose-demo.yaml up --detach db
        until [ $(docker inspect --format="{{ .State.Health.Status }}") -eq "healthy" ]; \
        do sleep 5; done
        
    # - name: Server unit tests
    #   # guarantee test.log will always be clean
    #   # test.log is to be in the `custom-backend` crate
    #   run: |
    #     echo > test.log
    #     cargo test --lib
    # - name: Server integration tests
    #   run: |
    #     cargo test --test tls_on_default --
    #     cargo test --test tls_off_switch -- --no-tls
    #   #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
