name: Archie CI

on:
  push:
    branches: [ "main", "testing" ]

jobs:

  server_tests:

    runs-on: ubuntu-24.0.4

    steps:
    - uses: actions/checkout@v4   # checks out the repo
    - name: Build server
      run: cargo build --verbose
    - name: Server - unit tests
      run: 
        # guarantee test.log will always be clean
        echo > test.log
        cargo test --lib
    - name: Server - integration tests
      run:
        cargo test --test tls_on_default --
        cargo test --test tls_off_switch -- --no-tls
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
