name: Archie CI

on:
  push:
    branches: [ "testing" ]

jobs:

  server_tests:

    runs-on: ubuntu-latest
    env:
      EX_VAR: "a value/here"      # an env var to test env fetches
      SERVER_SOCKET: "127.0.0.1:4321"
      PRE_LOG: 1                  # suppressed initial stdout, for backgrounding
      MYSQL_PASSWORD: thepass     # not real pw; doesnt matter for testing
      MYSQL_ROOT_PASSWORD: root
      DB_URL: "mysql://server1:thepass@127.0.0.1:3306/archie"

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4
    - name: Set up MySQL database
      # uses demo db, identical to real db except in content
      # running this first so that the database can initialize while
      # the server builds 
      run: 
        docker compose 
        --file compose-demo.yaml 
        --file test-helpers/testing-override.yaml
        up 
        --detach db
    - name: Server unit tests
      run: |
        cd ./custom-backend
        echo > test.log
        cargo test --lib
        cargo test --test tls_on_default --
        cargo test --test tls_off_switch -- --no-tls
    - name: Server integration tests
      run: |
        echo "developing these tests..."
    - name: Test DB's dump-on-exit (shutdown and prelim check)
      run: |
        docker compose down
        bash test-helpers/validate-dump.sh
